builds:
  - binary: pipe
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=0

dockers:
  - 
    binary: pipe
    image: quay.io/nicholasjackson/pipe
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    tag_templates: 
      - "{{ .Version }}"
      - "{{ .Tag }}"
      - latest
  - 
    binary: pipe
    image: quay.io/nicholasjackson/pipe
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile.arm7
    tag_templates: 
      - "arm7-{{ .Tag }}"
      - "arm7-{{ .Version }}"
