// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package web

import (
	"net/http"
	"sync"
)

var (
	lockConnectionPoolMockGetConnection sync.RWMutex
)

// ConnectionPoolMock is a mock implementation of ConnectionPool.
//
//     func TestSomethingThatUsesConnectionPool(t *testing.T) {
//
//         // make and configure a mocked ConnectionPool
//         mockedConnectionPool := &ConnectionPoolMock{
//             GetConnectionFunc: func(server string, port string) (*http.Server, error) {
// 	               panic("TODO: mock out the GetConnection method")
//             },
//         }
//
//         // TODO: use mockedConnectionPool in code that requires ConnectionPool
//         //       and then make assertions.
//
//     }
type ConnectionPoolMock struct {
	// GetConnectionFunc mocks the GetConnection method.
	GetConnectionFunc func(server string, port string) (*http.Server, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetConnection holds details about calls to the GetConnection method.
		GetConnection []struct {
			// Server is the server argument value.
			Server string
			// Port is the port argument value.
			Port string
		}
	}
}

// GetConnection calls GetConnectionFunc.
func (mock *ConnectionPoolMock) GetConnection(server string, port string) (*http.Server, error) {
	if mock.GetConnectionFunc == nil {
		panic("moq: ConnectionPoolMock.GetConnectionFunc is nil but ConnectionPool.GetConnection was just called")
	}
	callInfo := struct {
		Server string
		Port   string
	}{
		Server: server,
		Port:   port,
	}
	lockConnectionPoolMockGetConnection.Lock()
	mock.calls.GetConnection = append(mock.calls.GetConnection, callInfo)
	lockConnectionPoolMockGetConnection.Unlock()
	return mock.GetConnectionFunc(server, port)
}

// GetConnectionCalls gets all the calls that were made to GetConnection.
// Check the length with:
//     len(mockedConnectionPool.GetConnectionCalls())
func (mock *ConnectionPoolMock) GetConnectionCalls() []struct {
	Server string
	Port   string
} {
	var calls []struct {
		Server string
		Port   string
	}
	lockConnectionPoolMockGetConnection.RLock()
	calls = mock.calls.GetConnection
	lockConnectionPoolMockGetConnection.RUnlock()
	return calls
}
