// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package web

import (
	"github.com/nicholasjackson/pipe/logger"
	"sync"
)

var (
	lockConnectionPoolMockGetConnection sync.RWMutex
)

// ConnectionPoolMock is a mock implementation of ConnectionPool.
//
//     func TestSomethingThatUsesConnectionPool(t *testing.T) {
//
//         // make and configure a mocked ConnectionPool
//         mockedConnectionPool := &ConnectionPoolMock{
//             GetConnectionFunc: func(bindAddr string, port int, log logger.Logger) (Connection, error) {
// 	               panic("TODO: mock out the GetConnection method")
//             },
//         }
//
//         // TODO: use mockedConnectionPool in code that requires ConnectionPool
//         //       and then make assertions.
//
//     }
type ConnectionPoolMock struct {
	// GetConnectionFunc mocks the GetConnection method.
	GetConnectionFunc func(bindAddr string, port int, log logger.Logger) (Connection, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetConnection holds details about calls to the GetConnection method.
		GetConnection []struct {
			// BindAddr is the bindAddr argument value.
			BindAddr string
			// Port is the port argument value.
			Port int
			// Log is the log argument value.
			Log logger.Logger
		}
	}
}

// GetConnection calls GetConnectionFunc.
func (mock *ConnectionPoolMock) GetConnection(bindAddr string, port int, log logger.Logger) (Connection, error) {
	if mock.GetConnectionFunc == nil {
		panic("moq: ConnectionPoolMock.GetConnectionFunc is nil but ConnectionPool.GetConnection was just called")
	}
	callInfo := struct {
		BindAddr string
		Port     int
		Log      logger.Logger
	}{
		BindAddr: bindAddr,
		Port:     port,
		Log:      log,
	}
	lockConnectionPoolMockGetConnection.Lock()
	mock.calls.GetConnection = append(mock.calls.GetConnection, callInfo)
	lockConnectionPoolMockGetConnection.Unlock()
	return mock.GetConnectionFunc(bindAddr, port, log)
}

// GetConnectionCalls gets all the calls that were made to GetConnection.
// Check the length with:
//     len(mockedConnectionPool.GetConnectionCalls())
func (mock *ConnectionPoolMock) GetConnectionCalls() []struct {
	BindAddr string
	Port     int
	Log      logger.Logger
} {
	var calls []struct {
		BindAddr string
		Port     int
		Log      logger.Logger
	}
	lockConnectionPoolMockGetConnection.RLock()
	calls = mock.calls.GetConnection
	lockConnectionPoolMockGetConnection.RUnlock()
	return calls
}
