// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package providers

import ()

var ()

// ConnectionPoolMock is a mock implementation of ConnectionPool.
//
//     func TestSomethingThatUsesConnectionPool(t *testing.T) {
//
//         // make and configure a mocked ConnectionPool
//         mockedConnectionPool := &ConnectionPoolMock{
//         }
//
//         // TODO: use mockedConnectionPool in code that requires ConnectionPool
//         //       and then make assertions.
//
//     }
type ConnectionPoolMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
