// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package worker

import (
	"github.com/nats-io/nats"
	"sync"
)

var (
	lockNatsConnectionMockPublish        sync.RWMutex
	lockNatsConnectionMockQueueSubscribe sync.RWMutex
)

// NatsConnectionMock is a mock implementation of NatsConnection.
//
//     func TestSomethingThatUsesNatsConnection(t *testing.T) {
//
//         // make and configure a mocked NatsConnection
//         mockedNatsConnection := &NatsConnectionMock{
//             PublishFunc: func(subj string, data []byte) error {
// 	               panic("TODO: mock out the Publish method")
//             },
//             QueueSubscribeFunc: func(subj string, queue string, cb nats.MsgHandler) (*nats.Subscription, error) {
// 	               panic("TODO: mock out the QueueSubscribe method")
//             },
//         }
//
//         // TODO: use mockedNatsConnection in code that requires NatsConnection
//         //       and then make assertions.
//
//     }
type NatsConnectionMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(subj string, data []byte) error

	// QueueSubscribeFunc mocks the QueueSubscribe method.
	QueueSubscribeFunc func(subj string, queue string, cb nats.MsgHandler) (*nats.Subscription, error)

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Subj is the subj argument value.
			Subj string
			// Data is the data argument value.
			Data []byte
		}
		// QueueSubscribe holds details about calls to the QueueSubscribe method.
		QueueSubscribe []struct {
			// Subj is the subj argument value.
			Subj string
			// Queue is the queue argument value.
			Queue string
			// Cb is the cb argument value.
			Cb nats.MsgHandler
		}
	}
}

// Publish calls PublishFunc.
func (mock *NatsConnectionMock) Publish(subj string, data []byte) error {
	if mock.PublishFunc == nil {
		panic("moq: NatsConnectionMock.PublishFunc is nil but NatsConnection.Publish was just called")
	}
	callInfo := struct {
		Subj string
		Data []byte
	}{
		Subj: subj,
		Data: data,
	}
	lockNatsConnectionMockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	lockNatsConnectionMockPublish.Unlock()
	return mock.PublishFunc(subj, data)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//     len(mockedNatsConnection.PublishCalls())
func (mock *NatsConnectionMock) PublishCalls() []struct {
	Subj string
	Data []byte
} {
	var calls []struct {
		Subj string
		Data []byte
	}
	lockNatsConnectionMockPublish.RLock()
	calls = mock.calls.Publish
	lockNatsConnectionMockPublish.RUnlock()
	return calls
}

// QueueSubscribe calls QueueSubscribeFunc.
func (mock *NatsConnectionMock) QueueSubscribe(subj string, queue string, cb nats.MsgHandler) (*nats.Subscription, error) {
	if mock.QueueSubscribeFunc == nil {
		panic("moq: NatsConnectionMock.QueueSubscribeFunc is nil but NatsConnection.QueueSubscribe was just called")
	}
	callInfo := struct {
		Subj  string
		Queue string
		Cb    nats.MsgHandler
	}{
		Subj:  subj,
		Queue: queue,
		Cb:    cb,
	}
	lockNatsConnectionMockQueueSubscribe.Lock()
	mock.calls.QueueSubscribe = append(mock.calls.QueueSubscribe, callInfo)
	lockNatsConnectionMockQueueSubscribe.Unlock()
	return mock.QueueSubscribeFunc(subj, queue, cb)
}

// QueueSubscribeCalls gets all the calls that were made to QueueSubscribe.
// Check the length with:
//     len(mockedNatsConnection.QueueSubscribeCalls())
func (mock *NatsConnectionMock) QueueSubscribeCalls() []struct {
	Subj  string
	Queue string
	Cb    nats.MsgHandler
} {
	var calls []struct {
		Subj  string
		Queue string
		Cb    nats.MsgHandler
	}
	lockNatsConnectionMockQueueSubscribe.RLock()
	calls = mock.calls.QueueSubscribe
	lockNatsConnectionMockQueueSubscribe.RUnlock()
	return calls
}
