// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package nats

import (
	"github.com/nats-io/go-nats-streaming"
	"sync"
)

var (
	lockConnectionMockPublish        sync.RWMutex
	lockConnectionMockQueueSubscribe sync.RWMutex
)

// ConnectionMock is a mock implementation of Connection.
//
//     func TestSomethingThatUsesConnection(t *testing.T) {
//
//         // make and configure a mocked Connection
//         mockedConnection := &ConnectionMock{
//             PublishFunc: func(subj string, data []byte) error {
// 	               panic("TODO: mock out the Publish method")
//             },
//             QueueSubscribeFunc: func(subject string, qgroup string, cb stan.MsgHandler, opts ...stan.SubscriptionOption) (stan.Subscription, error) {
// 	               panic("TODO: mock out the QueueSubscribe method")
//             },
//         }
//
//         // TODO: use mockedConnection in code that requires Connection
//         //       and then make assertions.
//
//     }
type ConnectionMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(subj string, data []byte) error

	// QueueSubscribeFunc mocks the QueueSubscribe method.
	QueueSubscribeFunc func(subject string, qgroup string, cb stan.MsgHandler, opts ...stan.SubscriptionOption) (stan.Subscription, error)

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Subj is the subj argument value.
			Subj string
			// Data is the data argument value.
			Data []byte
		}
		// QueueSubscribe holds details about calls to the QueueSubscribe method.
		QueueSubscribe []struct {
			// Subject is the subject argument value.
			Subject string
			// Qgroup is the qgroup argument value.
			Qgroup string
			// Cb is the cb argument value.
			Cb stan.MsgHandler
			// Opts is the opts argument value.
			Opts []stan.SubscriptionOption
		}
	}
}

// Publish calls PublishFunc.
func (mock *ConnectionMock) Publish(subj string, data []byte) error {
	if mock.PublishFunc == nil {
		panic("moq: ConnectionMock.PublishFunc is nil but Connection.Publish was just called")
	}
	callInfo := struct {
		Subj string
		Data []byte
	}{
		Subj: subj,
		Data: data,
	}
	lockConnectionMockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	lockConnectionMockPublish.Unlock()
	return mock.PublishFunc(subj, data)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//     len(mockedConnection.PublishCalls())
func (mock *ConnectionMock) PublishCalls() []struct {
	Subj string
	Data []byte
} {
	var calls []struct {
		Subj string
		Data []byte
	}
	lockConnectionMockPublish.RLock()
	calls = mock.calls.Publish
	lockConnectionMockPublish.RUnlock()
	return calls
}

// QueueSubscribe calls QueueSubscribeFunc.
func (mock *ConnectionMock) QueueSubscribe(subject string, qgroup string, cb stan.MsgHandler, opts ...stan.SubscriptionOption) (stan.Subscription, error) {
	if mock.QueueSubscribeFunc == nil {
		panic("moq: ConnectionMock.QueueSubscribeFunc is nil but Connection.QueueSubscribe was just called")
	}
	callInfo := struct {
		Subject string
		Qgroup  string
		Cb      stan.MsgHandler
		Opts    []stan.SubscriptionOption
	}{
		Subject: subject,
		Qgroup:  qgroup,
		Cb:      cb,
		Opts:    opts,
	}
	lockConnectionMockQueueSubscribe.Lock()
	mock.calls.QueueSubscribe = append(mock.calls.QueueSubscribe, callInfo)
	lockConnectionMockQueueSubscribe.Unlock()
	return mock.QueueSubscribeFunc(subject, qgroup, cb, opts...)
}

// QueueSubscribeCalls gets all the calls that were made to QueueSubscribe.
// Check the length with:
//     len(mockedConnection.QueueSubscribeCalls())
func (mock *ConnectionMock) QueueSubscribeCalls() []struct {
	Subject string
	Qgroup  string
	Cb      stan.MsgHandler
	Opts    []stan.SubscriptionOption
} {
	var calls []struct {
		Subject string
		Qgroup  string
		Cb      stan.MsgHandler
		Opts    []stan.SubscriptionOption
	}
	lockConnectionMockQueueSubscribe.RLock()
	calls = mock.calls.QueueSubscribe
	lockConnectionMockQueueSubscribe.RUnlock()
	return calls
}
